# .project metadata for Kubewarden
# Documentation: https://github.com/cncf/automation/tree/main/utilities/dot-project

schema_version: "1.0.0"
slug: "kubewarden"
name: "Kubewarden"
description: "Kubewarden is a Policy Engine powered by WebAssembly policies. Its policies can be written in CEL, Rego (OPA & Gatekeeper flavours), Rust, Go, YAML, and others. Kubewarden simplifies Policy-As-Code by allowing policy authors and consumers to use their preferred tooling and stack, develop and test policies out of cluster. "
type: "project"
project_lead: "flavio"
slack_channels:
  - name: "#kubewarden"
    link: "https://kubernetes.slack.com/"
    primary: true
  - name: "#kubewarden-dev"
    link: "https://kubernetes.slack.com/"

maturity_log:
  - phase: "sandbox"
    date: "2022-06-17T00:00:00Z"
    issue: "https://github.com/cncf/sandbox/issues/213"

repositories:
  - "https://github.com/kubewarden/adm-controller"
  - "https://github.com/kubewarden/sbomscanner"
  - "https://github.com/kubewarden/policies"
  - "https://github.com/kubewarden/helm-charts"
  - "https://github.com/kubewarden/rego-policies-library"

website: "https://www.kubewarden.io"

artwork: "https://landscape.cncf.io/logos/kubewarden.svg"

adopters:
  path: "https://github.com/kubewarden/community/blob/main/ADOPTERS.md"

package_managers:
  ghcr.io: "kubewarden"

social:
  bluesky: "https://bsky.app/profile/kubewarden.io"
  mastodon: "https://hachyderm.io/@kubewarden"
  twitter: "https://twitter.com/kubewarden"

security:
  policy:
    path: "https://github.com/kubewarden/.github/blob/main/SECURITY.md"
  contact:
    advisory_url: "https://github.com/kubewarden/adm-controller/security/advisories/new"
    email: "cncf-kubewarden-maintainers@lists.cncf.io"

governance:
  governance_doc:
    path: "https://github.com/kubewarden/community/blob/main/GOVERNANCE.md"
  contributing:
    path: "https://github.com/kubewarden/community/blob/main/CONTRIBUTING.md"
  code_of_conduct:
    path: "https://github.com/cncf/foundation/blob/main/code-of-conduct.md"
  contributor_ladder:
    path: "https://github.com/kubewarden/community/blob/main/CONTRIBUTOR_LADDER.md"
  maintainer_lifecycle:
    progression_ladder:
      path: "https://github.com/kubewarden/community/blob/main/CONTRIBUTOR_LADDER.md"

legal:
  license:
    path: "https://github.com/kubewarden/adm-controller/blob/main/LICENSE"
  identity_type:
    has_dco: true
    has_cla: false
    dco_url:
      path: "https://developercertificate.org/"

documentation:
  readme:
    path: "https://github.com/kubewarden/adm-controller/blob/main/README.md"
  support:
    path: "https://docs.kubewarden.io"
  api:
    path: "https://docs.kubewarden.io/admission-controller/latest/en/reference/CRDs.html"

landscape:
  category: "Provisioning"
  subcategory: "Security & Compliance"

# CLOMonitor Score: 99/100
# Documentation: 100 | License: 100 | Best Practices: 100 | Security: 92
